def test(bot):
    if bot.from_id == 63475046:
        bot.send("Тест показал, что ты нужен во мне", attachment="photo-169151978_459236875")
    elif bot.from_id == 234601719:
        bot.send("Все хуйня, давай по новой!", attachment="photo-169151978_459236876")
    elif bot.from_id == 401547026:
        bot.send("Все идёт согласно плану", attachment="photo-169151978_457729185")
    else:
        bot.send("Тест проведён удачно.")


def anton(bot):
    bot.send('Бота Антона тут нет... Приходите завтра.')


cmd = {
    test: ["тест", "test"],
    anton: ["антон", "anton"]
}

var = {
    "кал": {"access": 0, "file": "calc.py", "type": "All"},
    "time": {"access": 0, "file": "time.py", "type": "All"},
    "имя": {"access": 0, "file": "names.py", "type": "All"},
    "names": {"access": 0, "file": "names.py", "type": "All"},
    "имена": {"access": 0, "file": "names.py", "type": "All"},
    "антон": {"access": 0, "file": "anton.py", "type": "All"},
    "подсказка": {"access": 0, "file": "podskazka.py", "type": "All"},
    "промо": {"access": 0, "file": "promo.py", "type": "All"},
    "котик": {"access": 0, "file": "cat.py", "type": "All"},
    "кот": {"access": 0, "file": "cat.py", "type": "All"},
    "киска": {"access": 0, "file": "cat.py", "type": "All"},
    "cat": {"access": 0, "file": "cat.py", "type": "All"},
    "профиль": {"access": 0, "file": "profile.py", "type": "All"},
    "profile": {"access": 0, "file": "profile.py", "type": "All"},
    "беседа": {"access": 0, "file": "beseda.py", "type": "All"},
    "конфа": {"access": 0, "file": "beseda.py", "type": "All"},
    "инвентарь": {"access": 0, "file": "inventory.py", "type": "All"},
    "inventory": {"access": 0, "file": "inventory.py", "type": "All"},
    "инв": {"access": 0, "file": "inventory.py", "type": "All"},
    "inv": {"access": 0, "file": "inventory.py", "type": "All"},
    "разрешить поиск": {"access": 0, "file": "OnFiend.py", "type": "Chat"},
    "разреши поиск": {"access": 0, "file": "OnFiend.py", "type": "Chat"},
    "запретить поиск": {"access": 0, "file": "OffFiend.py", "type": "Chat"},
    "запрети поиск": {"access": 0, "file": "OffFiend.py", "type": "Chat"},
    "разрешить диалог": {"access": 0, "file": "OnDialog.py", "type": "Chat"},
    "разреши диалог": {"access": 0, "file": "OnDialog.py", "type": "Chat"},
    "запретить диалог": {"access": 0, "file": "OffDialog.py", "type": "Chat"},
    "запрети диалог": {"access": 0, "file": "OffDialog.py", "type": "Chat"},
    "магазин": {"access": 0, "file": "shop.py", "type": "All"},
    "мгз": {"access": 0, "file": "shop.py", "type": "All"},
    "shop": {"access": 0, "file": "shop.py", "type": "All"},
    "id": {"access": 0, "file": "id.py", "type": "All"},
    "ид": {"access": 0, "file": "id.py", "type": "All"},
    "лоли": {"access": 0, "file": "loli.py", "type": "All"},
    "некололи": {"access": 0, "file": "nekololi.py", "type": "All"},
    "аниме": {"access": 0, "file": "anime.py", "type": "All"},
    "цит": {"access": 0, "file": "cit.py", "type": "All"},
    "цитата": {"access": 0, "file": "citata.py", "type": "All"},
    "цитата2": {"access": 0, "file": "citata2.py", "type": "All"},
    "рейтинг": {"access": 0, "file": "reiting.py", "type": "All"},
    "богачи": {"access": 0, "file": "reitingmoney.py", "type": "All"},
    "stata": {"access": 0, "file": "status.py", "type": "All"},
    "стат": {"access": 0, "file": "status.py", "type": "All"},
    "статус": {"access": 0, "file": "status.py", "type": "All"},
    "стата": {"access": 0, "file": "status.py", "type": "All"},
    "пороль": {"access": 0, "file": "password.py", "type": "All"},
    "пароль": {"access": 0, "file": "password.py", "type": "All"},
    "курс": {"access": 0, "file": "kursvalut.py", "type": "All"},
    "валюты": {"access": 0, "file": "kursvalut.py", "type": "All"},
    "валюта": {"access": 0, "file": "kursvalut.py", "type": "All"},
    "музыка": {"access": 0, "file": "music.py", "type": "All"},
    "монетка": {"access": 0, "file": "monetka.py", "type": "All"},
    "видео": {"access": 0, "file": "video.py", "type": "All"},
    "док": {"access": 0, "file": "doc.py", "type": "All"},
    "доки": {"access": 0, "file": "doc.py", "type": "All"},
    "docs": {"access": 0, "file": "doc.py", "type": "All"},
    "гифки": {"access": 0, "file": "gif.py", "type": "All"},
    "гифка": {"access": 0, "file": "gif.py", "type": "All"},
    "гиф": {"access": 0, "file": "gif.py", "type": "All"},
    "gif": {"access": 0, "file": "gif.py", "type": "All"},
    "gifs": {"access": 0, "file": "gif.py", "type": "All"},
    "фото": {"access": 0, "file": "photo.py", "type": "All"},
    "photo": {"access": 0, "file": "photo.py", "type": "All"},
    "photos": {"access": 0, "file": "photo.py", "type": "All"},
    "фотки": {"access": 0, "file": "photo.py", "type": "All"},
    "скажи": {"access": 0, "file": "voice.py", "type": "All"},
    "say": {"access": 0, "file": "voice.py", "type": "All"},
    "вики": {"access": 0, "file": "wiki.py", "type": "All"},
    "wiki": {"access": 0, "file": "wiki.py", "type": "All"},
    "выбери": {"access": 0, "file": "viberi.py", "type": "All"},
    "хуй": {"access": 0, "file": "xue.py", "type": "All"},
    "когда": {"access": 0, "file": "kogda.py", "type": "All"},
    "рандомная цитата": {"access": 0, "file": "random_citata.py", "type": "All"},
    "кто": {"access": 0, "file": "kto.py", "type": "Chat"},
    "кого": {"access": 0, "file": "kogo.py", "type": "Chat"},
    "шанс": {"access": 0, "file": "chance.py", "type": "All"},
    "оскорби": {"access": 0, "file": "posli.py", "type": "All"},
    "топ": {"access": 0, "file": "top.py", "type": "Chat"},
    "включи автокик": {"access": 0, "file": "OnAutokick.py", "type": "Chat"},
    "выключи автокик": {"access": 0, "file": "OffAutokick.py", "type": "Chat"},
    "включить автокик": {"access": 0, "file": "OnAutokick.py", "type": "Chat"},
    "выключить автокик": {"access": 0, "file": "OffAutokick.py", "type": "Chat"},
    "сцп": {"access": 0, "file": "scp.py", "type": "All"},
    "scp": {"access": 0, "file": "scp.py", "type": "All"},
    "ладно": {"access": 0, "file": "ladno.py", "type": "All"},
    "python": {"access": 0, "file": "python.py", "type": "All"},
    "информация": {"access": 0, "file": "info.py", "type": "All"},
    "инфо": {"access": 0, "file": "info.py", "type": "All"},
    "помощь": {"access": 0, "file": "helps.py", "type": "All"},
    "помошь": {"access": 0, "file": "helps.py", "type": "All"},
    "комманды": {"access": 0, "file": "helps.py", "type": "All"},
    "команды": {"access": 0, "file": "helps.py", "type": "All"},
    "тест": {"access": 0, "file": "test.py", "type": "All"},
    "эмодзи": {"access": 0, "file": "smile.py", "type": "All"},
    "смайлик": {"access": 0, "file": "smile.py", "type": "All"},
    "smile": {"access": 0, "file": "smile.py", "type": "All"},
    "бунт": {"access": 0, "file": "bunt.py", "type": "All"},
    "бунд": {"access": 0, "file": "bunt.py", "type": "All"},
    "vip": {"access": 0, "file": "vip.py", "type": "All"},
    "вип": {"access": 0, "file": "vip.py", "type": "All"},
    "пинг": {"access": 0, "file": "ping.py", "type": "All"},
    "переводчик": {"access": 0, "file": "translate.py", "type": "All"},
    "языки": {"access": 0, "file": "langs.py", "type": "All"},
    "взрыв": {"access": 0, "file": "vzriv.py", "type": "Chat"},
    "кража": {"access": 0, "file": "kraza.py", "type": "Chat"},

    "приветствие": {"access": 0, "file": "ChangeWelcome.py", "type": "Chat"},
    "включить приветствие": {"access": 0, "file": "OnWelcome.py", "type": "Chat"},
    "включи приветствие": {"access": 0, "file": "OnWelcome.py", "type": "Chat"},
    "отключить приветствие": {"access": 0, "file": "OffWelcome.py", "type": "Chat"},
    "отключи приветствие": {"access": 0, "file": "OffWelcome.py", "type": "Chat"},
    "выключить приветствие": {"access": 0, "file": "OffWelcome.py", "type": "Chat"},
    "выключи приветствие": {"access": 0, "file": "OffWelcome.py", "type": "Chat"},

    "прощание": {"access": 0, "file": "proshanie.py", "type": "Chat"},
    "включить прощание": {"access": 0, "file": "OnGoodBye.py", "type": "Chat"},
    "включи прощание": {"access": 0, "file": "OnGoodBye.py", "type": "Chat"},
    "отключить прощание": {"access": 0, "file": "OffGoodBye.py", "type": "Chat"},
    "отключи прощание": {"access": 0, "file": "OffGoodBye.py", "type": "Chat"},

    "стандартное приветствие": {"access": 0, "file": "DefaultWelcome.py", "type": "Chat"},
    "offwelcome": {"access": 0, "file": "OffWelcome.py", "type": "Chat"},
    "offgoodbye": {"access": 0, "file": "OffGoodBye.py", "type": "Chat"},
    "onwelcome": {"access": 0, "file": "OnWelcome.py", "type": "Chat"},
    "ongoodbye": {"access": 0, "file": "OnGoodBye.py", "type": "Chat"},
    "welcome": {"access": 0, "file": "ChangeWelcome.py", "type": "Chat"},
    "defaultwelcome": {"access": 0, "file": "DefaultWelcome.py", "type": "Chat"},
    "kick": {"access": 0, "file": "kick.py", "type": "Chat"},
    "кик": {"access": 0, "file": "kick.py", "type": "Chat"},
    "запрети": {"access": 0, "file": "zapreti.py", "type": "Chat"},
    "block": {"access": 0, "file": "zapreti.py", "type": "Chat"},
    "разреши": {"access": 0, "file": "razreshi.py", "type": "Chat"},
    "unblock": {"access": 0, "file": "razreshi.py", "type": "Chat"},
    "гороскоп": {"access": 0, "file": "goroskop.py", "type": "All"},
    "донатеры": {"access": 0, "file": "donaters.py", "type": "All"},
    "погода": {"access": 0, "file": "pogoda.py", "type": "All"},
    "подборка": {"access": 0, "file": "podborka.py", "type": "All"},
    "включи автораспознавание": {"access": 249, "file": "AutoRaspoznanieOn.py", "type": "Chat"},
    "выключить автораспознавание": {"access": 249, "file": "AutoRaspoznanieOff.py", "type": "Chat"},
    "отключить автораспознавание": {"access": 249, "file": "AutoRaspoznanieOff.py", "type": "Chat"},
    "включи автораспознание": {"access": 249, "file": "AutoRaspoznanieOn.py", "type": "Chat"},
    "включи автораспознание": {"access": 249, "file": "AutoRaspoznanieOn.py", "type": "Chat"},
    "выключи автораспознание": {"access": 249, "file": "AutoRaspoznanieOff.py", "type": "Chat"},
    "отключи автораспознание": {"access": 249, "file": "AutoRaspoznanieOff.py", "type": "Chat"},
    "позови": {"access": 0, "file": "pozovi.py", "type": "Chat"},
    "созови": {"access": 0, "file": "pozovi.py", "type": "Chat"},
    "созвать": {"access": 0, "file": "pozovi.py", "type": "Chat"},
    "коуб": {"access": 249, "file": "coub.py", "type": "All"},
    "дешифр": {"access": 249, "file": "desifr.py", "type": "All"},
    "шифр": {"access": 249, "file": "sifr.py", "type": "All"},
    "анонимка": {"access": 249, "file": "anonimkainfo.py", "type": "All"},
    "анон": {"access": 249, "file": "anonimka.py", "type": "All"},
    "setrank": {"access": 249, "file": "setrank.py", "type": "All"},
    "ранг": {"access": 249, "file": "setrank.py", "type": "All"},
    "перевод": {"access": 249, "file": "translate.py", "type": "All"},
    "переведи": {"access": 249, "file": "translate.py", "type": "All"},
    "онлайн": {"access": 249, "file": "online.py", "type": "Chat"},
    "бaн": {"access": 250, "file": "fakeban.py", "type": "Chat"},
    "скрин": {"access": 249, "file": "screen.py", "type": "All"},
    "инфа": {"access": 249, "file": "infa.py", "type": "All"},
    "праздник": {"access": 249, "file": "prazdnik.py", "type": "All"},
    "праздники": {"access": 249, "file": "prazdnik.py", "type": "All"},
    "празник": {"access": 249, "file": "prazdnik.py", "type": "All"},
    "празники": {"access": 249, "file": "prazdnik.py", "type": "All"},
    "хентай": {"access": 249, "file": "hentai.py", "type": "All"},
    "hentai": {"access": 249, "file": "hentai.py", "type": "All"},
    "распознай": {"access": 249, "file": "raspoznai.py", "type": "All"},
    "шазам": {"access": 249, "file": "shazam.py", "type": "All"},
    "пост": {"access": 249, "file": "post.py", "type": "All"},
    "бан": {"access": 250, "file": "ban.py", "type": "All"},
    "ban": {"access": 250, "file": "ban.py", "type": "All"},
    "разбан": {"access": 250, "file": "unban.py", "type": "All"},
    "unban": {"access": 250, "file": "unban.py", "type": "All"},
    "банкик": {"access": 250, "file": "bankick.py", "type": "Chat"},
    "bankick": {"access": 250, "file": "bankick.py", "type": "Chat"},
    "clear": {"access": 252, "file": "clearmedia.py", "type": "All"},
    "покажи": {"access": 252, "file": "infouser.py", "type": "All"},
    "lolifind": {"access": 252, "file": "lolifind.py", "type": "All"},
    "nekololifind": {"access": 252, "file": "nekololifind.py", "type": "All"},
    "akick": {"access": 252, "file": "akick.py", "type": "All"},
    "moder": {"access": 252, "file": "moderinfo.py", "type": "All"},
    "givevip": {"access": 253, "file": "givevip.py", "type": "All"},
    "delvip": {"access": 253, "file": "delvip.py", "type": "All"},
    "givemoder": {"access": 253, "file": "givemoder.py", "type": "All"},
    "glmoder": {"access": 253, "file": "glmoderinfo.py", "type": "All"},
    "предупредить": {"access": 254, "file": "warn.py", "type": "All"},
    "предупреди": {"access": 254, "file": "warn.py", "type": "All"},
    "нарушение": {"access": 254, "file": "warn.py", "type": "All"},
    "логи": {"access": 254, "file": "logs.py", "type": "All"},
    "проверить": {"access": 254, "file": "proverit.py", "type": "All"},
    "giverank": {"access": 254, "file": "giverank.py", "type": "All"},
    "giveglmoder": {"access": 254, "file": "giveglmoder.py", "type": "All"},
    "agivevip": {"access": 254, "file": "agivevip.py", "type": "All"},
    "addvip": {"access": 254, "file": "addvip.py", "type": "All"},
    "vipdown": {"access": 254, "file": "vipdown.py", "type": "All"},
    "zam": {"access": 253, "file": "zamadminainfo.py", "type": "All"},
    "py": {"access": 253, "file": "py.py", "type": "All"},
    "additem": {"access": 253, "file": "additem.py", "type": "All"},
    "!": {"access": 254, "file": "terminal.py", "type": "All"},
    "оповести": {"access": 254, "file": "opovesti.py", "type": "All"},
    "adddonate": {"access": 255, "file": "adddonate.py", "type": "All"},
    "tempcmd": {"access": 255, "file": "Temp.py", "type": "All"},
    "addnewitem": {"access": 254, "file": "addnewitem.py", "type": "All"},
    "кмдап": {"access": 254, "file": "cmdup.py", "type": "All"},
    "смдап": {"access": 254, "file": "cmdup.py", "type": "All"},
    "cmdup": {"access": 254, "file": "cmdup.py", "type": "All"},
    "/": {"access": 254, "file": "foranton.py", "type": "All"}
}
